### DISCUSSION TITLE
Dynamic Date Range

### DISCUSSION THREAD

**Discussion by baspax1** [dylandoamaral/uptime-card#143] [Q&A]
Hi i want to have possibility to change this date range for like this:
https://prnt.sc/1q2sglZkyNuD
Want to have ability to have a clickable '6 days ago' to go to previous week or month or something like that, is it possible?

can you give me an example please on my card?
```
type: custom:uptime-card
bar:
  spacing: 5
  amount: 36
  height: 20
  round: 4
icon: mdi:network
status_adaptive_color: true
severity: 100
hours_to_show: 144
entity: binary_sensor.vasw_pc
alias:
  ko: 'Off'
  ok: 'On'
```
