### DISCUSSION TITLE
Get ko value in average_template

### DISCUSSION THREAD

**Discussion by agneevX** [dylandoamaral/uptime-card#78] [Q&A] [answered]
I was thinking of getting the downtime % for my card:

```yaml
# uptime
average_template: '[[[ return variables.uptime.toFixed(1); ]]]% up'
# downtime
average_template: '[[[ return 100 - variables.uptime.toFixed(1); ]]]% down'
```

However that returns:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/19761269/117866952-592edc00-b2b5-11eb-95d4-87d6720046d6.png">

Do you have any ideas?
