### ISSUE TITLE
Rendering as circles is not correct

### ISSUE THREAD

**Issue by ee02217** [dylandoamaral/uptime-card#114]
I have been using this card, and I love it.
But some recent update may have screwed how I want this to present.

This is my configuration:
```
type: custom:uptime-card
ok: home
ko: not_home
bar:
  height: 10
  round: 100
show:
  header: true
  title: true
  icon: true
  status: true
  timeline: true
  footer: true
  average: true
name: Raspberry
entity: device_tracker.raspberrypi
```

And now, as you can see, it doesn't show the full "circles" (getting cut the bottom:
![image](https://user-images.githubusercontent.com/60232595/147939815-f7b6d36f-4d59-471d-a4f5-72de1aefe543.png)
