### ISSUE TITLE
Ping not working on browsers (chrome, firefox)

### ISSUE THREAD

**Issue by 29axe** [dylandoamaral/uptime-card#12]
Hi,
Thank you for this awesome addon. I've been looking for something like this for a long time (default history graph is a bit ugly).

I have an issue on browsers (firefox and chrome on both android and windows 10, all up-to-date). 
I tried to reproduce your example with the ping status and it's working fine on the mobile app but when I connected to lovelace on chrome/firefox, all bars are grey except the last one that is orange (with uptime value at ~ 0.xx percent).
I took screenshots to illustrate.

On chrome (and firefox too)
![Screenshot_20210326-234714_Chrome](https://user-images.githubusercontent.com/8787921/112700527-a8988480-8e8e-11eb-9ce2-39dde274bb71.jpg)

On Home Assistant app on Android
![Screenshot_20210326-234733_Home Assistant](https://user-images.githubusercontent.com/8787921/112700530-a9311b00-8e8e-11eb-828b-be95aa3b06e5.jpg)
 
Versions of HA:
Core: core-2021.3.4
Supervisor: supervisor-2021.03.6
HACS: 1.11.3 (frontend: 20210214110032)
uptime-card: v0.0.1 & v0.0.2 (installed and upgraded using HACS)
Home Assistant Android: 2021.3.1-full

I also have a question regarding your example 3. Why do you set 'ko' to 'o'? Looking at the documentation I would have expected something like 'ok: ok' and 'ko: ko' but it's not working untill I set to 'ok: on' and 'ko: off' or 'ko: o'.

config (I used mainly the lovelace UI to configure):
```yaml
type: vertical-stack
cards:
  - type: 'custom:uptime-card'
    icon: 'mdi:router-wireless'
    severity: 100
    hours_to_show: 72
    color:
      ok: '#45C669'
      ko: '#C66445'
      none: '#C9C9C9'
      half: '#C6B145'
    bar:
      height: 46
      round: 1
      spacing: 4
      amount: 36
    alias: {}
    entity: binary_sensor.router_ping
    name: Routeur
    ok: 'on'
    ko: 'off'
  - type: 'custom:uptime-card'
    entity: binary_sensor.netplus_dns_1
    icon: 'mdi:dns'
    severity: 100
    name: DNS1
    ko: 'off'
    bar:
      height: 46
      round: 1
      spacing: 4
      amount: 36
    hours_to_show: 72
    ok: 'on'
```
