### ISSUE TITLE
entity id is displayed instead of name

### ISSUE THREAD

**Issue by YvesZH** [dylandoamaral/uptime-card#121]
Maybe I'm doing something wrong, but the entity id (without domain) is displayed for me instead of the defined name.  here my config:

```
    - type: custom:uptime-card
      bar:
        height: 18
        amount: 32
      color_thresholds:
        - value: 0
          color: rgb(245,245,245)
        - value: 5
          color: rgb(255,228,181)
        - value: 30
          color: rgb(244,164,96)
        - value: 100
          color: rgb(210,105,30)
      color:
        ok: '#C66445'
        ko: '#aaaaaa'
        half: '#FFE4B5'
      alias: {}
      entity: binary_sensor.buro_bewegungsmelder_esph_naehtisch
      tooltip:
        hour24: true
        animation: true
      hours_to_show: 8
      show:
        average: false
        footer: false
        timeline: true
        icon: false
        header: true
        status: true
        title: true
      name: Büro (PIR)
```

and this is how it looks:

![15B57B9E-C054-46F3-BD2E-CBF21630BA7B](https://user-images.githubusercontent.com/64573990/163554567-25f4ddc0-09a6-4eed-8524-5ff842785565.jpeg)
