### ISSUE TITLE
History not shown for non-binary sensors

### ISSUE THREAD

**Issue by tYn0** [dylandoamaral/uptime-card#129]
Yesterday I created non-binary sensors for checking the state of services running on my media server. Sensor state is either "Online" or "Offline", card displays the state correctly but bars are set to "None":

```
type: custom:uptime-card
entity: sensor.service_monitor_deluge
ok: Online
ko: Offline
icon_adaptive_color: true
hours_to_show: 24
bar:
  round: 4
  amount: 24
```

![image](https://user-images.githubusercontent.com/10382681/173135180-51fd4005-72c0-4e35-a10e-d031cac832bc.png)
![image](https://user-images.githubusercontent.com/10382681/173135349-4d9cfbe8-f9e0-47a0-91ee-2765c1a6496d.png)

**Comment by dylandoamaral** [comment]
I see nothing wrong here, you still have the issue ?

**Comment by tYn0** [comment]
Not sure if I am misunderstanding how the card should work but shouldnt all bars in the screenshot be green? Either way I played around with it and put a few cards in entities card to get a nicer display:
![image](https://user-images.githubusercontent.com/10382681/173192385-c0ee4c52-53cc-4b45-87dc-64ae5a521ddf.png)
When I refresh the page it sometimes "works" - here Deluge sensor isn't working even though it should:
![image](https://user-images.githubusercontent.com/10382681/173192452-05a9810d-bad1-4843-9058-3b58a3958c81.png)
```
type: entities
entities:
  - type: custom:uptime-card
    entity: sensor.service_monitor_plex
    title_template: Plex
    ok: Online
    ko: Offline
    hours_to_show: 24
    icon_adaptive_color: true
    show:
      footer: false
      status: false
    bar:
      amount: 24
      round: 6
  - type: custom:uptime-card
    entity: sensor.service_monitor_deluge
    title_template: Deluge
    ok: Online
    ko: Offline
    hours_to_show: 24
    icon_adaptive_color: true
    show:
      footer: false
      status: false
    bar:
      amount: 24
      round: 6
  - type: custom:uptime-card
    entity: sensor.service_monitor_nzbget
    title_template: NZBGet
    ok: Online
    ko: Offline
    hours_to_show: 24
    icon_adaptive_color: true
    show:
      footer: false
      status: false
    bar:
      amount: 24
      round: 6
  - type: custom:uptime-card
    entity: sensor.service_monitor_sonarr
    title_template: Sonarr
    ok: Online
    ko: Offline
    hours_to_show: 24
    icon_adaptive_color: true
    show:
      footer: false
      status: false
    bar:
      amount: 24
      round: 6
  - type: custom:uptime-card
    entity: sensor.service_monitor_radarr
    title_template: Radarr
    ok: Online
    ko: Offline
    hours_to_show: 24
    icon_adaptive_color: true
    show:
      footer: false
      status: false
    bar:
      amount: 24
      round: 6
  - type: custom:uptime-card
    entity: sensor.service_monitor_prowlarr
    title_template: Prowlarr
    ok: Online
    ko: Offline
    hours_to_show: 24
    icon_adaptive_color: true
    show:
      footer: false
      status: false
    bar:
      amount: 24
      round: 6
```
I also noticed some errors regarding the uptime-card in console:
![image](https://user-images.githubusercontent.com/10382681/173192747-64e8f4e8-213a-46de-9cd2-b2816315fea4.png)
