### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by HITChris** [dylandoamaral/uptime-card#13]
On both Chrome and Edge, I'm getting a ton of console errors... even with a very basic card config. Apologies if this represents misconfiguration on my part, but any ideas?

```          - type: 'custom:uptime-card'
            entity: sensor.broadcasting_system
            icon: 'mdi:raspberry-pi'
            ok: Online
            alias:
              ok: Fully Online
            bar:
              height: 23
              round: 1
              spacing: 3
              amount: 24
            name: Broadcasting
            hours_to_show: 24
            icon_adaptive_color: true
            status_adaptive_color: true
            average_text: '% uptime'
```
![image](https://user-images.githubusercontent.com/34664460/112738250-290ec200-8f2f-11eb-8d74-a5db1e69a3e5.png)

![image](https://user-images.githubusercontent.com/34664460/112738244-21e7b400-8f2f-11eb-8d23-7f6674d00a66.png)

Above sensor is usually 'Online', but it can be set to 4 or 5 different values. Even so, I tried the same config with a simpler 'ping' binary sensor, and the console errors remained.

**Comment by dylandoamaral** [comment]
Hello, thank you, no there is no error in your configuration ^^'. Sadly I can't reproduce the bug even using a multi states sensors such as `weather.home`. It seems that you can't fetch the API, maybe an old version of home assistant? I will add a fix to avoid such an error but you will not be able to fetch any state from the api itself :/.

**Comment by dylandoamaral** [comment]
Don't hesitate to reopen the issue if the error still remain after `version 0.0.3` (or trying the current pre release version js file).

**Comment by HITChris** [comment]
Very odd. I'm current on HA (Supervised) / Chrome. I'm confused by what you mean by not being able to fetch the API? The entity's history shows up. I guess we'll just wait to see if this pops up for anyone else, in case we can cross-reference our circumstances

**Comment by dylandoamaral** [comment]
I will reopen this issue since it seems pretty weird to me, I was thinking that maybe your version had an API problem but it is certainly no the case. However, I can't reproduce your issue can you tell me exactly how I can reproduce this behavior from scratch ? Maybe a way to reproduce the `sensor.broadcasting_system` without a lot of overhead ?

**Comment by HITChris** [comment]
**Similar sensor -**

```
- platform: template
  sensors:
    electrical_system:
      friendly_name: "Electrical"
      value_template: >-
        {% if states.sensor.ups_status_data_full.state != "On Battery" and states.sensor.ups_status_data_full.state != "Offline"  %}
          Online
        {% else %}
          {% set iL = namespace(issueList = '') %}
          {% if states.sensor.ups_status_data_full.state == "On Battery" %}
            {% set iL.issueList = 'Power' %}
          {% endif %}
          {% if states.sensor.ups_status_data_full.state == "Offline" %}
            {% if iL.issueList|length %}
              {% set iL.issueList = iL.issueList + ", UPS Component" %}
            {% else %}
              {% set iL.issueList = "UPS Component" %}
            {% endif %}
          {% endif %}
          {% if ',' in iL.issueList %}
            Faults Detected ({{iL.issueList}})
          {% else %}
            Fault Detected ({{iL.issueList}})
          {% endif %}
        {% endif %}
```

![image](https://user-images.githubusercontent.com/34664460/112882440-98e98d80-9092-11eb-8da5-9da5b848efac.png)

**Card -** 

```
title: My Test Dash
views:
  - path: default_view
    title: Home
    cards:
      - type: 'custom:uptime-card'
        entity: sensor.electrical_system
        icon: 'mdi:flash'
        ok: Online
        alias:
          ok: Fully Online
        bar:
          height: 23
          round: 1
          spacing: 3
          amount: 24
        name: Electrical
        hours_to_show: 24
        icon_adaptive_color: true
        status_adaptive_color: true
        average_text: '% uptime'
```
![a](https://user-images.githubusercontent.com/34664460/112882535-b3236b80-9092-11eb-88fc-5660e34cd4ea.PNG)

![image](https://user-images.githubusercontent.com/34664460/112882855-1dd4a700-9093-11eb-8396-5846af3be859.png)

(unknown states == HA restarts. P.S., little history in this case... but only b/c I created this entity 30 mins ago)

**Chrome -** 

![b](https://user-images.githubusercontent.com/34664460/112883142-7c018a00-9093-11eb-8f59-a62ffb2b81a1.PNG)

![c](https://user-images.githubusercontent.com/34664460/112882546-b74f8900-9092-11eb-9d9f-dac24f6a3faa.PNG)

![d](https://user-images.githubusercontent.com/34664460/112882555-b9194c80-9092-11eb-9d9b-9599b7a2acd5.PNG)

HA is core-2021.3.4, Supervisor is supervisor-2021.03.6
