### ISSUE TITLE
Latest version v0.12.0 breaks what was working fine.

### ISSUE THREAD

**Issue by Gferretta** [dylandoamaral/uptime-card#140]
Hi

When updating all my uptime-card they stopped working showing incorrect data, and when going back to the previous version they work fine.

For example, I have the sensor for Rpi Power Status, which is always green, without problems, and after updating everything turned red showing failure.

Rrolled back to v0.11.1

Regards

**Comment by WarC0zes** [comment]
Same problem, additionally:

v0.11.1
![uptime-bar 0 11 0](https://user-images.githubusercontent.com/91471397/199368275-d3bc6ac4-9c15-476f-9dfa-25d57a8b30ad.png)

v0.12.0
![uptime-bar 0 12 0](https://user-images.githubusercontent.com/91471397/199368289-be219d6d-846c-473c-8b05-91b0ea2b239f.png)

```
  - type: custom:uptime-card
    entity: binary_sensor.rpi_power_status
    title_template: RPi3 B Tension
    ok: 'off'
    ko: 'on'
    bar:
      amount: 48
      round: 2
      height: 37
    hours_to_show: 48
    init:
      animation: raise
    color:
      title: rgb(68, 115, 158)
      ko: rgb(250, 0, 1)
      ok: green
    title_adaptive_color: false
    icon_adaptive_color: true
    tooltip_adaptive_color: true
    status_adaptive_color: true
    show:
      header: true
      title: true
      timeline: true
      footer: true
      average: true
    tooltip:
      hour24: true
      animation: true
    alias:
      ok: OK
      ko: Danger
    tap_action:
      action: more-info
    alignment:
      icon_first: true
      status: left
      tooltip_first: true
      header: spaced
```
