### ISSUE TITLE
OK / KO with numeric status?

### ISSUE THREAD

**Issue by qJake** [dylandoamaral/uptime-card#144]
I'm trying to use this card with the **Glances** integration, which only provides numeric statuses. I would prefer not to create a sensor template for each server that I'm trying to monitor.

Is it possible for the `ok` / `ko` values to monitor a numeric value?

It would be awesome if I could do something like this:

```yaml
entity: sensor.my_server_process_count
ok: 0
ok_num_compare: 'greater'
```

Or use a template:

```yaml
entity: sensor.my_server_process_count
ok: [[[ return parseInt(variables.current) > 0; ]]]
```

Is this possible today? If not, could it be considered for a future release?
