### ISSUE TITLE
Multiple items on one card

### ISSUE THREAD

**Issue by plandregan** [dylandoamaral/uptime-card#161]
Is there an example how to add 3 items to display on the one card?

**Comment by hugo-leij** [comment]
See:
![image](https://github.com/dylandoamaral/uptime-card/assets/10241984/794ac3a6-635b-43cf-825d-3ca15ed67588)

```
type: custom:layout-card
layout_type: custom:horizontal-layout
layout:
  height: 1020px
cards:
  - type: custom:uptime-card
    entity: binary_sensor.gang_sensor_motion_detection
    ko_icon: mdi:motion-sensor
    ok: 'off'
    ko: 'on'
    icon: mdi:motion-sensor-off
    title_template: Gang
    hours_to_show: 12
    half: orange
    alias:
      ko: Beweging
      ok: Geen beweging
    color:
      icon: grey
    show:
      average: false
      footer: false
      timeline: true
      icon: true
      title: true
      header: true
    bar:
      amount: 72
      height: 30
    init: {}
    tooltip:
      hour24: false
    tap_action: {}
    blink: {}
    clip: {}
  - type: custom:uptime-card
    entity: binary_sensor.keuken_sensor_motion_detection
    ko_icon: mdi:motion-sensor
    ok: 'off'
    ko: 'on'
    icon: mdi:motion-sensor-off
    title_template: Keuken
    hours_to_show: 12
    half: orange
    alias:
      ko: Beweging
      ok: Geen beweging
    color:
      icon: grey
    show:
      average: false
      footer: false
      timeline: true
      icon: true
      title: true
      header: true
    bar:
      amount: 72
      height: 30
    init: {}
    tooltip:
      hour24: false
    tap_action: {}
    blink: {}
    clip: {}
  - type: custom:uptime-card
    entity: binary_sensor.overloop_sensor_motion_detection
    ko_icon: mdi:motion-sensor
    ok: 'off'
    ko: 'on'
    icon: mdi:motion-sensor-off
    title_template: Overloop
    hours_to_show: 12
    half: orange
    alias:
      ko: Beweging
      ok: Geen beweging
    color:
      icon: grey
    show:
      average: false
      footer: false
      timeline: true
      icon: true
      title: true
      header: true
    bar:
      amount: 72
      height: 30
    init: {}
    tooltip:
      hour24: false
    tap_action: {}
    blink: {}
    clip: {}
  - type: custom:uptime-card
    entity: binary_sensor.eetkamer_sensor_sensor_state_any
    ko_icon: mdi:motion-sensor
    ok: 'off'
    ko: 'on'
    icon: mdi:motion-sensor-off
    title_template: Eetkamer
    hours_to_show: 24
    half: orange
    alias:
      ko: Beweging
      ok: Geen beweging
    color:
      icon: grey
    show:
      average: false
      footer: false
      timeline: true
      icon: true
      title: true
      header: true
    bar:
      amount: 72
      height: 30
    init: {}
    tooltip:
      hour24: false
    tap_action: {}
    blink: {}
    clip: {}
  - type: custom:uptime-card
    entity: binary_sensor.eetkamer_deur_window_door_is_open
    ko_icon: mdi:door
    ok: 'off'
    ko: 'on'
    icon: mdi:door-closed
    title_template: Eetkamer
    hours_to_show: 12
    half: orange
    alias:
      ko: Beweging
      ok: Geen beweging
    color:
      icon: grey
    show:
      average: false
      footer: false
      timeline: true
      icon: true
      title: true
      header: true
    bar:
      height: 30
    init: {}
    tooltip:
      hour24: false
    tap_action: {}
    blink: {}
    clip: {}
  - type: custom:uptime-card
    entity: binary_sensor.woonkamer_schuifdeur_tuin_window_door_is_open
    ko_icon: mdi:door
    ok: 'off'
    ko: 'on'
    icon: mdi:door-closed
    title_template: Schuifpui
    hours_to_show: 12
    half: orange
    alias:
      ko: Open
      ok: Dicht
    color:
      icon: grey
    show:
      average: false
      footer: false
      timeline: true
      icon: true
      title: true
      header: true
    bar:
      height: 30
    init: {}
    tooltip:
      hour24: false
    tap_action: {}
    blink: {}
    clip: {}
  - type: custom:uptime-card
    entity: binary_sensor.gang_voordeur_window_door_is_open
    ko_icon: mdi:door
    ok: 'off'
    ko: 'on'
    icon: mdi:door-closed
    title_template: Voordeur
    hours_to_show: 12
    half: orange
    alias:
      ko: Open
      ok: Dicht
    color:
      icon: grey
    show:
      average: false
      footer: false
      timeline: true
      icon: true
      title: true
      header: true
    bar:
      height: 30
    init: {}
    tooltip:
      hour24: false
    tap_action: {}
    blink: {}
    clip: {}

```
