### ISSUE TITLE
url tap action to ourside URL

### ISSUE THREAD

**Issue by stefanbode** [dylandoamaral/uptime-card#162]
I want to jump to the webinterface of the device. "url" is not supported and "url_path" is not doing what I hoped. I somebody able to add "url" with the corresponding action to open url in a new tab???

```
tap_action:
  action: url
  url_path: |
    [[[ 'http://' + states('sensor.badrollo_ip') ]]]
```
