### ISSUE TITLE
Numeric Range Visualization

### ISSUE THREAD

**Issue by awilliams84** [dylandoamaral/uptime-card#163]
I am trying to display a sensor to show the range of power throughout the day. This usually returns a numeric value 190-230. But right now its showing as "unknown" and I see no value in the footer.

```
type: custom:uptime-card
entity: sensor.upstairs_hallway_lamp_rms_voltage_2
icon: mdi:lightning-bolt
title_template: House Power
hours_to_show: 168
status_adaptive_color: true
color_thresholds:
  - value: 200
    color: red
  - value: 205
    color: yellow
  - value: 210
    color: green
show:
  footer: true
average_template: '[[[ return variables.current; ]]]% uptime'
```
