### ISSUE TITLE
Sun not work ...

### ISSUE THREAD

**Issue by andrewjswan** [dylandoamaral/uptime-card#32]
I add card from example, but card show always night (sun icon work ok)

```
type: 'custom:uptime-card'
icon: 'mdi:weather-sunny'
entity: sun.sun
name: Sun
ok: above_horizon
ko: below_horizon
color:
  ok: '#C6B145'
  ko: '#053752'
  half: '#EF810E'
icon_adaptive_color: true
bar:
  spacing: 4
  height: 10
  round: 4
show:
  average: false
  status: false
```

Screenshot:
![image](https://user-images.githubusercontent.com/3609660/113303311-9f356f00-9309-11eb-9c85-e3fb557413e9.png)
