### ISSUE TITLE
Color thresholds buggy

### ISSUE THREAD

**Issue by agneevX** [dylandoamaral/uptime-card#66]
Hi!

Color thresholds seems buggy...

1. Historical data is showing different colors randomly
2. I'm seeing an undefined color (white), also randomly

```yaml
color_thresholds:
  - value: 95
    color: '#C66445'
  - value: 97
    color: '#C6B145'
  - value: 99
    color: '#45C669'
```

https://user-images.githubusercontent.com/19761269/115549540-6106ec00-a2c6-11eb-859a-6513efe57af1.mov

**Comment by agneevX** [comment]
Ok, so this seems to be an issue for values above the highest limit specified:

<img src="https://user-images.githubusercontent.com/19761269/116715527-6d8cf200-a9f4-11eb-9e8d-c5814d8e6c16.png" width="450">

<details><summary>Expand YAML code</summary>

```yaml
entity: binary_sensor.cloudflare_dns_ping
type: 'custom:uptime-card'
name: Internet
icon: 'mdi:ethernet-cable'
hours_to_show: 1
ko_icon: 'mdi:ethernet-cable-off'
title_adaptive_color: true
status_adaptive_color: true
icon_adaptive_color: true
color_thresholds:
  - value: 95
    color: '#C66445'
  - value: 97
    color: '#C6B145'
  - value: 99
    color: '#45C669'
tap_action:
  action: more-info
  haptic: light
bar:
  spacing: 4
  amount: 36
  height: 22
  round: 5
alias:
  ok: Online
  ko: Offline
```

</details>
