### ISSUE TITLE
Reverse the logic for problem device class

### ISSUE THREAD

**Issue by tetienne** [dylandoamaral/uptime-card#91]
Most of my binary sensors I used for this card have a device class set problem. From the [HA documentation](https://www.home-assistant.io/integrations/binary_sensor/):
> problem: on means problem detected, off means no problem (OK)

So it means that out of the box, this card reverse all the states for my binary sensors. I have to set the `ok` value to `off` and the `ko` value to `on`.

What do you think to apply a specific logic for this device class?

**Comment by dylandoamaral** [comment]
Hi, I think it is too specific and not very useful since you can still reverse yourself the status using:
```yaml
type: 'custom:uptime-card'
ko: on
ok: off
```
Or using the color mapping:
```yaml
type: 'custom:uptime-card'
color:
  ok: '#C66445'
  ko: '#45C669'
```
To be more precise, I don't want to make this kind of change because it may surprise the user of this card who expects the basic behaviour.

If you have many uptime card with the same yaml configuration, I suggest you to use: https://github.com/custom-cards/decluttering-card
